### ISSUE TITLE
New Radar Chart

### ISSUE THREAD

**Issue by jamesleesaunders** [jamesleesaunders/d3-ez#114]
This request is to add a new Radar Chart (and component) to d3-ez.

The Radar Chart should be added across 2 new files:
`/src/chart/radarChart.js`
`/src/component/radar.js`

Use pre-existing components for the circular axis and labels:
`/src/component/circularAxis.js`
`/src/component/circularSectorLabels.js`

As a base you could start with:
`/src/chart/polarAreaChart.js`

An new example file should also be created:
`/examples/RadarChartExample.html`

See the following example(s):
https://en.wikipedia.org/wiki/Radar_chart
https://datavizcatalogue.com/methods/radar_chart.html
http://datavizproject.com/data-type/radical-line-graph/

**Comment by jamesleesaunders** [comment]
Thanks Dip,

I have taken your files and imported them into the repo. Looking good and so nearly there!

I have also managed to finish off the color scale and legend so it now works well.
<img width="709" alt="screen shot 2018-07-09 at 22 53 44" src="https://user-images.githubusercontent.com/13055416/42478050-3059446c-83cb-11e8-8547-90dbfb6aa8fb.png">

You can take a look at the change I made here:
https://github.com/jamesleesaunders/d3-ez/blob/RadarChart/src/chart/radarChart.js
and
https://github.com/jamesleesaunders/d3-ez/blob/RadarChart/examples/RadarChartExample.html

There is still a little bit of work to do on the tool top section which I have commented out for now. I will try and get that going tomorrow.

The main change I made were:
* Fixed calculation of 'angleSlice' size.
* Swapped color scale to use group (series) names rather than category names.
* Swapping var's for let's (To make ES6 compliant).
* Few other odds and ends.

It is looking much better now.

Thanks for all your help Dip! You are a super star!

Once we have it fully working the next step is to move the radar generation code into its own mini component which is then called by the parent chartRadar.js.

**Comment by DipParmar** [comment]
Dear Jim,

You are really appreciative :) but I really feel that You are actual Super
Star.

Thanks and Regards,
Dip Parmar

**Comment by jamesleesaunders** [comment]
Hi @DipParmar
I have polished off the Radar chart and moved some of the code to a new component.
I have just published v3.3.12 which includes your contributions.
Thanks again. Now you know more of the inside of d3-ez if you do think of any additions to the docs & README.md please feel free to raise a pull request for any changes.
All the best,
Jim

**Comment by DipParmar** [comment]
Sure... because of you I learned a lot from this library like how to manage
functionality and all with abstract approach.

Currently I am in preparation to join other company so still going through
the process.. so I just need two week break, once it will be complete I
will definitely going to contribute more or you can just assign me some
task I will start from there as soon as I complete the process.

Best Regards,
Dip
