### ISSUE TITLE
Angular support

### ISSUE THREAD

**Issue by vrecon** [jamesleesaunders/d3-ez#127]
Hi,
Are there any plans to support angular 2+. I love your library and its functions and would love to use it in serveral angular projects.

**Comment by jamesleesaunders** [comment]
Hi, thanks for your interest in d3-ez. There are no plans for Angular support at present (I have never used Angular).
However I would welcome any contributions to d3-ez if you feel it is possible to add support?
If you have any other questions please ask! I am very keen to support anyone who uses d3-ez!

**Comment by jamesleesaunders** [comment]
You may also be interested in my other spin off project 
https://github.com/jamesleesaunders/d3-x3d 

d3-ez is for svg based charts
d3-x3d for X3D data viz generation - basically 3D charts.
