### ISSUE TITLE
Using in webpack?

### ISSUE THREAD

**Issue by dimm0** [jamesleesaunders/d3-ez#132]
I'm trying to import the library in vue.js+webpack

```
import * as d3Base from 'd3'
import { d3ez } from 'd3-ez'
const d3 = Object.assign(d3Base, { d3ez })
```

(according to https://www.giacomodebidda.com/how-to-import-d3-plugins-with-webpack/)

d3.ez is still undefined

Could you please provide an example how to do this properly?

Thanks!

**Comment by jamesleesaunders** [comment]
Hi,
Sorry for delay in response.
Did you manage to get it to work? 
I have not ever loaded d3-ez like that with Object.assign.
When I get a moment I will have a go myself.

Jim

**Comment by jamesleesaunders** [comment]
Both these works:
```
import d3Ez from "d3-ez";
```
```
const d3Ez = require("d3-ez");
```
