### ISSUE TITLE
Importing d3-ez

### ISSUE THREAD

**Issue by trieucrew** [jamesleesaunders/d3-ez#143]
Is there a way to imort ez? I keep getting the error: 
Attempted import error: 'ez' is not exported from 'd3' (imported as 'd3').

I have tried these but no luck
`
import {ez} from 'd3-ez';
`

`
let d3ez = require('d3-ez');
`

**Comment by jamesleesaunders** [comment]
Hi,
Sorry for delay in response.
Did you manage to get it to work? `let d3ez = require('d3-ez');` should work.
See it in use on this Observable Notebook https://observablehq.com/@jamesleesaunders/bishop-currys-royal-wedding-speech-analysis-with-d3-ez   (scroll to bottom).

Jim

**Comment by jamesleesaunders** [comment]
Both these works:
```
import d3Ez from "d3-ez";
```
```
let d3Ez = require("d3-ez");
```
